/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.exam2question11.view;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItmExit = new javax.swing.JMenuItem();
        mnuProduct = new javax.swing.JMenu();
        mnuItmSell = new javax.swing.JMenuItem();
        mnuSeller = new javax.swing.JMenu();
        mnuItmPunchC = new javax.swing.JMenuItem();
        mnuStorage = new javax.swing.JMenu();
        mnuItmMonitorStock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        mnuItmExit.setText("Exit");
        mnuItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItmExit);

        jMenuBar1.add(mnuFile);

        mnuProduct.setText("Product");

        mnuItmSell.setText("Sell");
        mnuProduct.add(mnuItmSell);

        jMenuBar1.add(mnuProduct);

        mnuSeller.setText("Seller");

        mnuItmPunchC.setText("Punch the Card");
        mnuSeller.add(mnuItmPunchC);

        jMenuBar1.add(mnuSeller);

        mnuStorage.setText("Storage");

        mnuItmMonitorStock.setText("Monitor Stock");
        mnuStorage.add(mnuItmMonitorStock);

        jMenuBar1.add(mnuStorage);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmExitActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Exit?");
            if(i == 0)
            {
                frmLogin login = new frmLogin();
                login.setVisible(true);
                this.setVisible(false);
            }
    }//GEN-LAST:event_mnuItmExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItmExit;
    private javax.swing.JMenuItem mnuItmMonitorStock;
    private javax.swing.JMenuItem mnuItmPunchC;
    private javax.swing.JMenuItem mnuItmSell;
    private javax.swing.JMenu mnuProduct;
    private javax.swing.JMenu mnuSeller;
    private javax.swing.JMenu mnuStorage;
    // End of variables declaration//GEN-END:variables
}
