/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.model;

/**
 *
 * @author Lenovo
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1File = new javax.swing.JMenu();
        jMenuItem2Exit = new javax.swing.JMenuItem();
        jMenu2Product = new javax.swing.JMenu();
        jMenuItem3Sell = new javax.swing.JMenuItem();
        jMenu4Seller = new javax.swing.JMenu();
        jMenuItem4Punch = new javax.swing.JMenuItem();
        jMenu5Storage = new javax.swing.JMenu();
        jMenuItem5MonitorStock = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1File.setText("File");

        jMenuItem2Exit.setText("Exit");
        jMenuItem2Exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jMenuItem2ExitKeyTyped(evt);
            }
        });
        jMenu1File.add(jMenuItem2Exit);

        jMenuBar1.add(jMenu1File);

        jMenu2Product.setText("Product");

        jMenuItem3Sell.setText("Sell");
        jMenu2Product.add(jMenuItem3Sell);

        jMenuBar1.add(jMenu2Product);

        jMenu4Seller.setText("Seller");

        jMenuItem4Punch.setText("Punch the card");
        jMenu4Seller.add(jMenuItem4Punch);

        jMenuBar1.add(jMenu4Seller);

        jMenu5Storage.setText("Storage ");

        jMenuItem5MonitorStock.setText("Monitor Stok");
        jMenu5Storage.add(jMenuItem5MonitorStock);

        jMenuBar1.add(jMenu5Storage);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ExitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem2ExitKeyTyped
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ExitKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1File;
    private javax.swing.JMenu jMenu2Product;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4Seller;
    private javax.swing.JMenu jMenu5Storage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2Exit;
    private javax.swing.JMenuItem jMenuItem3Sell;
    private javax.swing.JMenuItem jMenuItem4Punch;
    private javax.swing.JMenuItem jMenuItem5MonitorStock;
    // End of variables declaration//GEN-END:variables
}
