/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.view;

/**
 *
 * @author Inforlan
 */
public class frmRegisterVenicule extends javax.swing.JFrame {

    /**
     * Creates new form frmRegisterVenicule
     */
    public frmRegisterVenicule() {
        initComponents();
        setLocation(400,200);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblLicensePlate = new javax.swing.JLabel();
        lblFondoRegisterCar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MAZDA", "CHEVROLET", "KIA", "HYUNDAI", "JEEP", "WOLKSVAGEN", "BMW", "PEUGEOT" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, 30));

        lblColor.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color:");
        lblColor.setToolTipText("Insert the brand of car(chevrolet,mazda,kia,etc)");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 66, -1));

        lblBrand.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblBrand.setText("Brand:");
        lblBrand.setToolTipText("Insert the brand of car(chevrolet,mazda,kia,etc)");
        getContentPane().add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 66, -1));

        lblLicensePlate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblLicensePlate.setForeground(new java.awt.Color(255, 255, 255));
        lblLicensePlate.setText("License Plate:");
        lblLicensePlate.setToolTipText("Insert the brand of car(chevrolet,mazda,kia,etc)");
        getContentPane().add(lblLicensePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        lblFondoRegisterCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/view/images/carfondoRegisterVehicule.jpg"))); // NOI18N
        getContentPane().add(lblFondoRegisterCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegisterVenicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegisterVenicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegisterVenicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegisterVenicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegisterVenicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFondoRegisterCar;
    private javax.swing.JLabel lblLicensePlate;
    // End of variables declaration//GEN-END:variables
}
